<a href="https://colab.research.google.com/github/SammriddhGupta/ISAA/blob/main/ISAA_Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Topic: Machine Learning based Malware Analysis 

## Performance Metrics for Classification to Look out for :
1. Accuracy

2. Precision 

3. Recall 

4. F1 score 

5. ROC 

6. AUC 

7. Discounted Cumulative Gain 

## Introduction to Logistic Regression

### Importing the libraries

In [26]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
import datetime
import pytz

### Printing the current date and time

In [27]:
current_time = datetime.datetime.now(pytz.timezone('Asia/Kolkata'))

# printing current time in india
print("The current time in india is :", current_time)

The current time in india is : 2022-08-14 00:13:26.232289+05:30


### Importing the dataset

In [28]:
dataset = pd.read_csv("/content/Malware_dataset.csv")

In [29]:
dataset2 = dataset.copy()
print("The current time in india is :", current_time)

The current time in india is : 2022-08-14 00:13:26.232289+05:30


In [30]:
dataset.head()

hash  millisecond  \
0  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            0   
1  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            1   
2  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            2   
3  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            3   
4  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...            4   

  classification  state  usage_counter        prio  static_prio  normal_prio  \
0        malware      0              0  3069378560        14274            0   
1        malware      0              0  3069378560        14274            0   
2        malware      0              0  3069378560        14274            0   
3        malware      0              0  3069378560        14274            0   
4        malware      0              0  3069378560        14274            0   

   policy  vm_pgoff  ...  nivcsw  min_flt  maj_flt  fs_excl_counter  \
0       0         0  ...       0        0      120                0   
1       0         0  ...       0        0      120                0   
2       0         0  ...       0        0      120                0   
3       0         0  ...       0        0      120                0   
4       0         0  ...       0        0      120                0   

         lock   utime  stime  gtime  cgtime  signal_nvcsw  
0  3204448256  380690      4      0       0             0  
1  3204448256  380690      4      0       0             0  
2  3204448256  380690      4      0       0             0  
3  3204448256  380690      4      0       0             0  
4  3204448256  380690      4      0       0             0  

[5 rows x 35 columns]

In [ ]:
print("The current time in india is :", current_time)

In [31]:
# we are dropping a column named classification in the copy of the dataset
dataset2 = dataset.drop(['classification'], axis=1)

In [ ]:
print("The current time in india is :", current_time)

In [32]:
X = dataset2.iloc[:,1:].values
y = dataset.iloc[:, 2].values

In [33]:
print("The current time in india is :", current_time)

The current time in india is : 2022-08-14 00:13:26.232289+05:30


In [34]:
print(X)

[[   0    0    0 ...    0    0    0]
 [   1    0    0 ...    0    0    0]
 [   2    0    0 ...    0    0    0]
 ...
 [ 997 4096    0 ...    0    0    0]
 [ 998 4096    0 ...    0    0    0]
 [ 999 4096    0 ...    0    0    0]]


In [35]:
print("The current time in india is :", current_time)

The current time in india is : 2022-08-14 00:13:26.232289+05:30


In [36]:
print(y)

['malware' 'malware' 'malware' ... 'malware' 'malware' 'malware']


### Label Encoding

In [37]:
from sklearn import preprocessing

In [38]:
print("The current time in india is :", current_time)

The current time in india is : 2022-08-14 00:13:26.232289+05:30


In [39]:
le = preprocessing.LabelEncoder()
y = le.fit_transform(y)

In [40]:
print(y)

[1 1 1 ... 1 1 1]


###Splitting the dataset into the Training set and Test set

In [41]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [42]:
print("The current time in india is :", current_time)

The current time in india is : 2022-08-14 00:13:26.232289+05:30


In [43]:
print(X_train)

[[  606 12288     0 ...    10     0     0]
 [  228 28672     0 ...     0     0     0]
 [  382  4096     0 ...     1     0     0]
 ...
 [  613 12288     0 ...    11     0     0]
 [  567  4096     0 ...     2     0     0]
 [  268     0     0 ...     0     0     0]]


In [44]:
print("The current time in india is :", current_time)

The current time in india is : 2022-08-14 00:13:26.232289+05:30


In [45]:
print(y_train)

[0 1 0 ... 0 0 1]


In [46]:
print(X_test)

[[    582       0       0 ...       8       0       0]
 [    498       0       0 ...       0       0       0]
 [    227 1028096       0 ...       4       0       0]
 ...
 [    585    4096       0 ...       0       0       0]
 [    519       0       0 ...       7       0       0]
 [    831       0       0 ...       0       0       0]]


In [47]:
print("The current time in india is :", current_time)

The current time in india is : 2022-08-14 00:13:26.232289+05:30


In [48]:
print(y_test)

[1 0 0 ... 1 0 0]


### Feature Scaling

In [49]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [50]:
print("The current time in india is :", current_time)

The current time in india is : 2022-08-14 00:13:26.232289+05:30


In [51]:
print(X_train)

[[ 0.36731703 -0.15969785  0.         ...  2.5559669   0.
   0.        ]
 [-0.941068   -0.14179605  0.         ... -0.50896701  0.
   0.        ]
 [-0.40802225 -0.16864875  0.         ... -0.20247362  0.
   0.        ]
 ...
 [ 0.39154638 -0.15969785  0.         ...  2.8624603   0.
   0.        ]
 [ 0.23232492 -0.16864875  0.         ...  0.10401977  0.
   0.        ]
 [-0.80261455 -0.1731242   0.         ... -0.50896701  0.
   0.        ]]


In [52]:
print("The current time in india is :", current_time)

The current time in india is : 2022-08-14 00:13:26.232289+05:30


In [53]:
print(X_test)

[[ 0.28424496 -0.1731242   0.         ...  1.94298012  0.
   0.        ]
 [-0.00650727 -0.1731242   0.         ... -0.50896701  0.
   0.        ]
 [-0.94452933  0.95021383  0.         ...  0.71700655  0.
   0.        ]
 ...
 [ 0.29462897 -0.16864875  0.         ... -0.50896701  0.
   0.        ]
 [ 0.06618079 -0.1731242   0.         ...  1.63648673  0.
   0.        ]
 [ 1.14611763 -0.1731242   0.         ... -0.50896701  0.
   0.        ]]


### Training Model on the Training set

In [54]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [55]:
print("The current time in india is :", current_time)

The current time in india is : 2022-08-14 00:13:26.232289+05:30


In [56]:
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
 intercept_scaling=1, l1_ratio=None, max_iter=100,
 multi_class='auto', n_jobs=None, penalty='l2',
 random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
 warm_start=False)

LogisticRegression(random_state=0)

### Predicting the Test set results

In [57]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 0]
 [0 0]]


In [58]:
print("The current time in india is :", current_time)

The current time in india is : 2022-08-14 00:13:26.232289+05:30


### Confusion Matrix and Accuracy

In [59]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11590   938]
 [  560 11912]]


0.94008

In [60]:
print("The current time in india is :", current_time)

The current time in india is : 2022-08-14 00:13:26.232289+05:30


## Introduction to Naive Bayes